### PR TITLE
Added "Falling Words" game

### PR DESCRIPTION
**Pull request by Specy**
I added my game, if it's approved i can work on it

### CODE REVIEW

**Comment by Specy** [comment]
Ok i finished the new game mentioned in #5 
Edit: i'm not sure why Vercel says that the build failed, i can't seem to be able to access the logs, but locally it builds fine

**Comment by aldy-san** [comment]
i've done review your code and check the log. this error is caused by some unused variable and missing react-hook. i put the log below.

image

Edit: I've tried the game you make, i want to ask how to enter the input? (i try using "space"), idk why my answer is wrong. 

image

**Comment by Specy** [comment]
It checks if the text falling is the same as the text you added, so what you write should be using the Japanese alphabet. I thought that users could learn how to learn the Japanese keyboard.

If you prefer I can put both the romanised and actual Japanese

**Comment by aldy-san** [comment]
thank you for adding romanised alphabet, but it still error cause react-hook missing dependency "loadGame". here the log below.

image

**Comment by Specy** [comment]
Also, the game restarts whenever you change the window width/height, this makes the content more responsive but causes an issue when opening the keyboard on android, should i remove it?

**Comment by aldy-san** [comment]
i think its good for now, i will merge your PR, thanks for contributing.

**Pull request merged**
